# Generated by Django 3.1.7 on 2021-03-13 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wish',
            options={'verbose_name_plural': 'Wishes'},
        ),
    ]
